const members = [
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '123',
        address: '0x002',
        firstName: 'First2',
        lastName: 'Last2',
        nickname: 'Nickname2',
        description: 'Short bio about the second member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
    {
        votingShares: '723',
        address: '0x001',
        firstName: 'First1',
        lastName: 'Last1',
        nickname: 'Nickname1',
        description: 'Short bio about the first member and stuff',
        dateJoined: '12/12/12',
        sponsoredBy: null,
    },
]

export default members